### ISSUE TITLE
Does It Available in Chrome Extension Store

### ISSUE THREAD

**Issue by li-xinyang** [meetDeveloper/Dictionary-Anywhere#1]
Does this extension available for Google Chrome? The link is to Mozilla Firefox store.

**Comment by meetDeveloper** [comment]
This extension is available in Mozilla Firefox as of now. I will soon, by tomorrow will also publish it on Google Chrome. Also there is another extension by [google  ](https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja?hl=en) that you can use in the meanwhile.

**Comment by li-xinyang** [comment]
Thanks for the response. I have tried the extension from Google but I do not like it due to its limited word definitions which requires me to open a new tab to find out more.

**Comment by meetDeveloper** [comment]
This extension uses define word, suppose you want to know meaning of hello, you google define hello, so my extension uses that.

**Comment by meetDeveloper** [comment]
I have made the extension for chrome, it is in currently in verification phase, and Google will check and review my extension, I will notify you once it is published.

**Comment by meetDeveloper** [comment]
@li-xinyang  It is available now on chrome webstore here. https://chrome.google.com/webstore/detail/dictionary-anywhere/hcepmnlphdfefjddkgkblcjkbpbpemac/. If you find any bugs or want to see new feature kindly open an issue on github, I will be glad to implement it.

**Comment by li-xinyang** [comment]
Thanks, I think I might help you with improving the extension visual style later point in time.

**Comment by meetDeveloper** [comment]
@li-xinyang What all can be changed in visual style?
