### ISSUE TITLE
Privacy issue

### ISSUE THREAD

**Issue by francescor** [meetDeveloper/Dictionary-Anywhere#11]
addon is great, thanks: it is simple and working, really, perfect!

Only one pretty serious privacy issue:

I handle my passwords with a password store application: and, of course, I cut and paste passwords all day long: my password store show me
* link
* username
* password

so I do, very often, cut and paste, in sequence, all these data :(

Now, of course, I do realize that with this extension, these data are read and used to find dictionary definitions, and this I think is pretty dangerous! I had to remove this addon, but I love it and want its functionality back.

how to solve? 
maybe by adding the option to have a word definition *not just* by selecting a word, but by using the right click on it once the word is selected (this would reduce useless traffic, too)

**Comment by meetDeveloper** [comment]
@francescor I have implemented this, will update the extension by today.

**Comment by meetDeveloper** [comment]
@francescor Added trigger key, update your extension, and see if that suits you.

**Comment by francescor** [comment]
wow, this is really great!
I confirm the update, and funcionality, thank you so much

**Comment by meetDeveloper** [comment]
@francescor Your issue was the one that pushed me to just sit this weekend and finish all the issues, I added languages also and also option to save history of words, so in a way thank you.
