### ISSUE TITLE
French - popup frozen in "search mode"

### ISSUE THREAD

**Issue by tigerjack** [meetDeveloper/Dictionary-Anywhere#14]
I was trying this add-on to have monolingual definition; while it seems to work for English words, that is not the case for French ones. Every time I double-click on a word, the pop-up is frozen in the same state of the attached picture
![image](https://user-images.githubusercontent.com/8199216/80184544-1434fa80-860b-11ea-962f-94f786d904d7.png)

**Comment by meetDeveloper** [comment]
@tigerjack I have fixed this and updated my extension, updated extension will be available shortly. Sorry I should have taken care of this earlier.

**Comment by meetDeveloper** [comment]
@akskos ^.

**Comment by meetDeveloper** [comment]
This bug has been fixed in v1.0.6 of the extension and the version is available on mozilla website, kindly update (It should automatically update, if automatic updates are not turned off). Sorry for the inconvenience. @tigerjack @akskos.
