### ISSUE TITLE
Save the words

### ISSUE THREAD

**Issue by dbads** [meetDeveloper/Dictionary-Anywhere#17]
It would be great to see an option in the meaning popup to save the word, so that I can go through them again in the future to memorize and all. 

May be the words can be stored in a file and let users know the words they save.

**Comment by meetDeveloper** [comment]
@dbads There is already such setting you can go to options and check the box that says save the word that I search for. Also can you tell me how can I make the more obvious to user that this options is given, it has been months since this option is given, I want to increase its reach. Thank you

**Comment by dbads** [comment]
@meetDeveloper oh yeah I see the option to download the history. Well this is what I think can be enhanced -
- An option to see the saved words in the bottom of the meaning popup beside more link
- Also, there could be a checkbox in the more row giving users more control to save or not save the word selected
- Format the saved words are exported can be better. and if possible those files can be stored on cloud and let users see/download them from there. Because Its more convenient to just go and see the words rather downloading the file again and again to see the words

**Comment by meetDeveloper** [comment]
@dbads Thanks for your input I will open new tickets for tracking this, closing this ticket as it might incorrectly portray that extension does not support saving words yet.
