### ISSUE TITLE
No longer working with any query

### ISSUE THREAD

**Issue by tienthanh8490** [meetDeveloper/Dictionary-Anywhere#20]
Hi, I first installed the extension 2 days ago and at that point everything works. Now whenever I click on an English word, it always return a "not found" result no matter how simple the word is. So I suspect something is off with the query. Not sure if it's because of my setup or it's due to the plugin. In any case, I'm happy to help, just let me know what steps are needed.

My setup: Firefox 78.0.2, macOS Mojave 10.14.

**Comment by meetDeveloper** [comment]
Could you open your console and check once what error if any does my extension is throwing?

**Comment by tienthanh8490** [comment]
Thanks, I just tried again and it works now. There is no error in console. Any clue what happened ?

**Comment by meetDeveloper** [comment]
Nope, no idea per say. I guess we can just wait to have this kind of issue happen again. Closing this till then. Thanks for using my extension.
