### ISSUE TITLE
Extension is storing the words and there is no way to disable it.

### ISSUE THREAD

**Issue by DyeffersonAz** [meetDeveloper/Dictionary-Anywhere#24]
I'm on Firefox 78.0.2, and I can't unable this option from the extension. When I deselect the option and save the settings, it still doesn't save when I refresh the tab.
![image](https://user-images.githubusercontent.com/16638560/88490076-5ace2400-cf6f-11ea-8f17-ab156366f0a6.png)

**Comment by meetDeveloper** [comment]
@DyeffersonAz sorry for the inconvenience, I will look into it.

**Comment by meetDeveloper** [comment]
@DyeffersonAz @mpaunovic This has been fixed in the latest release of extension, kindly update the extension. Let me know if you still face the problem.
