### ISSUE TITLE
the extension(ver: 1.0.6, last updated: August 4, 2020) is not working as before

### ISSUE THREAD

**Issue by endlessbest** [meetDeveloper/Dictionary-Anywhere#27]
this is an excellent extension, it worked well in a few days ago, but it constantly pop up "Sorry, no definition found"  whatever words are double clicked. did the update change something? i use firefox with proxy, please help.

**Comment by meetDeveloper** [comment]
Can you try once after turning off the proxy. I feel proxy is causing issue.

**Comment by endlessbest** [comment]
> 
> 
> Can you try once after turning off the proxy. I feel proxy is causing issue.

it's working today, i don't know what happened cause i still use the proxy. it may be my environment's issue but I'm not sure. thanks for replying, this is a gorgeous extension, i love it so much. would you like add a phonetic notation after the speaker icon if possible? there is enough space for that and would be great of help.

**Comment by endlessbest** [comment]
the problem occurs again, is there a way to show the debug info for locating the problem? i have to use the proxy cause I'm on the internal computer which can only access internet via proxy, there should no problem of the proxy cause i can post a comment here.

**Comment by meetDeveloper** [comment]
Can you check the logs that come in console, might be easier to debug it then @endlessbest

**Comment by endlessbest** [comment]
> 
> 
> Can you check the logs that come in console, might be easier to debug it then @endlessbest

i can see nothing in the console when i double click a word, the popup window is shown as expected. it is also strange that in the "Network" tab, it seems there is no url request, doesn't the dictionary grab its explanation on web? did i miss something?

**Comment by tsundokul** [comment]
@endlessbest check out #26, maybe it's the same problem, since you're using a proxy

**Comment by endlessbest** [comment]
> 
> 
> @endlessbest check out #26, maybe it's the same problem, since you're using a proxy

it may not be the same, i clearly remember that when the popup window says "Sorry, no definition found", i can still open the www.google.com and everything works fine besides this extension.  the extension is working well right now, when i press F12 to grab its network transmission, i can only see a "get" method which download the media file(mp3), how does it get the definition of the word?

**Comment by meetDeveloper** [comment]
You can open the browser console, you will find the request to fetch the meaning there. 
<img width="338" alt="Screenshot 2020-08-12 at 3 11 06 PM" src="https://user-images.githubusercontent.com/32453612/90000737-2916c600-dcae-11ea-9f97-2d54dbdbeff8.png">

**Comment by endlessbest** [comment]
> 
> 
> You can open the browser console, you will find the request to fetch the meaning there.
> <img alt="Screenshot 2020-08-12 at 3 11 06 PM" width="338" src="https://user-images.githubusercontent.com/32453612/90000737-2916c600-dcae-11ea-9f97-2d54dbdbeff8.png">

i installed this extension from [firefox add-ons manager](https://addons.mozilla.org/en-US/firefox/addon/dictionary-anyvhere), i can't see any console log, how can i get a debug version which has console output?

**Comment by meetDeveloper** [comment]
@endlessbest Do you see the request to fetch meaning in browser console?

**Comment by endlessbest** [comment]
> 
> 
> @endlessbest Do you see the request to fetch meaning in browser console?
> 
> <img alt="Screenshot 2020-08-12 at 3 38 38 PM" width="1270" src="https://user-images.githubusercontent.com/32453612/90003573-e5be5680-dcb1-11ea-8b73-1704aa4ec208.png">

no, that's strange, i can only see the request to fetch a media file. thanks for helping me all the time.
![1597627468(1)](https://user-images.githubusercontent.com/17191003/90349237-af932500-e06b-11ea-8c52-d1e13d8701a5.png)

**Comment by endlessbest** [comment]
it works well recently,  it could be something wrong with my network, thanks for the help
