### ISSUE TITLE
Dictionary double-click does not pop up in Firefox PDF viewer

### ISSUE THREAD

**Issue by MasonGreen365** [meetDeveloper/Dictionary-Anywhere#28]
Just installed extension, checked that boolean was enabled. When using the built-in PDF viewer on Firefox, there is no popup.

**Comment by meetDeveloper** [comment]
I will look into this.

**Comment by meetDeveloper** [comment]
Sorry for inconvenience, This can't be fixed because firefox does not allow content script to run in pdf.

More information: https://bugzilla.mozilla.org/show_bug.cgi?id=1454760

**Comment by tomislater** [comment]
Uhh, I miss this tool in PDF so much :/

Read Aloud add-on works in PDF files. Maybe something has changed? 🤔 BTW. I can help with that. I am going to research this topic soon.
