### ISSUE TITLE
Pop-up bubble not visible for BBC articles. 

### ISSUE THREAD

**Issue by Tobormai** [meetDeveloper/Dictionary-Anywhere#30]
When reading BBC article (sample below) pop-up bubble is displayed behind article_container. Can see outer edge of bubble in some instances so know it is working, but contents not readable. 

**Sample article**: https://www.bbc.com/future/article/20200918-the-fiasco-of-the-us-swine-flu-affair-of-1976.

**Comment by meetDeveloper** [comment]
@Tobormai Sorry for the inconvenience. This is caused by not having z-index, I have to research a bit and will fix this soon. Thank you for using my extension.

**Comment by Tobormai** [comment]
No worries. Thank you for taking the time to develop. Ah yes, z-index.
Teaching myself CSS so appreciate the feedback. Well done!

**Comment by meetDeveloper** [comment]
@Tobormai Sorry for the inconvenience caused. I have fixed the issue in v1.0.10. Extension will soon be updated on mozilla addons, it takes a little time for them to review the extension.

Really thank you for using my extension. :)
