### ISSUE TITLE
Always loading problem

### ISSUE THREAD

**Issue by sadam10am** [meetDeveloper/Dictionary-Anywhere#34]
When i double click a word it's always loading but never show result ,is this a internet problem or something else, i try to use google dictionary on Microsoft Edge and everything is fine.

**Comment by meetDeveloper** [comment]
@sadam10am It could be due to VPN, are you behind some proxy or connected to VPN?

**Comment by sadam10am** [comment]
Yes ,i must use VPN to connect to google.I switch to another addon called “English Popup Dictionary” and didn’t have any problems . 😊 How can I fix this if I want use “dictionary anywhere” ? Sent from Mail for Windows 10 From: meetDeveloperSent: Thursday, November 26, 2020 1:32 PMTo: meetDeveloper/Dictionary-AnywhereCc: sadam10am; MentionSubject: Re: [meetDeveloper/Dictionary-Anywhere] Always loading problem (#34) @sadam10am It could be due to VPN, are you behind some proxy or connected to VPN?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vertigo220** [comment]
Same problem, no VPN or proxy. Waterfox 2020.12 (64-bit).

**Comment by meetDeveloper** [comment]
Closing this in favor of #37.
