### ISSUE TITLE
Look-ups always have "Sorry no definition found"

### ISSUE THREAD

**Issue by Psion05** [meetDeveloper/Dictionary-Anywhere#36]
I don't know when it started, but recently, all definition look-ups give me the "Sorry no definition found" error. I've tried reloading the extension but the problem still persists.
A few examples below.
**First one**
![image](https://user-images.githubusercontent.com/31981653/99765141-7237ab00-2b24-11eb-9c46-c6f8c1487686.png)
**Second one**
![image](https://user-images.githubusercontent.com/31981653/99765181-8380b780-2b24-11eb-804c-465085e14a61.png)

**Comment by meetDeveloper** [comment]
I have fixed this in v1.0.8 and it will be soon available on firefox addon site in 2-3 days, they review and it sometime take time for addon to get published.

Sorry for any inconvenience caused, thank you for using my extension.

**Comment by meetDeveloper** [comment]
@Psion05 Closing this ticket in case you still find problem, kindly reopen it. :)

**Comment by Shahius** [comment]
Same thing started today. No definition found for everything. Nightly 136.0a1 (2025-01-10) (64-bit)
