### ISSUE TITLE
Not Populating Definitions in Firefox

### ISSUE THREAD

**Issue by cjung92** [meetDeveloper/Dictionary-Anywhere#4]
Have disabled/enable, reset Firefox, etc.

Popup is working, but definitions are not populating.

Firefox v69.0.1

**Comment by meetDeveloper** [comment]
I will fix this in this weekend, thank for using my extension, it feels good when someone from across the world is using the thing you made.

**Comment by meetDeveloper** [comment]
I actually fixed it, you can update and see if it works, thank for using my extension, it feels good when someone from across the world is using the thing you made.

**Comment by cjung92** [comment]
Updating it works! I had automatic updating on but it didn't update until I checked for updates manually I guess. Oh well.

Yours is the only inline dictionary I can find. All the other ones require more effort to use. Good work!

**Comment by meetDeveloper** [comment]
@cjung92 Thanks :)
