### ISSUE TITLE
The lookup isn't work anymore

### ISSUE THREAD

**Issue by huytd** [meetDeveloper/Dictionary-Anywhere#5]
I just noticed that the plugin doesn't work recently, it seems like Google just changed the UI, so the query selectors we're using isn't correct anymore.

I'll open a PR to fix that.

**Comment by meetDeveloper** [comment]
@huytd Does this still exist?

**Comment by huytd** [comment]
It's working now. Thanks @meetDeveloper 

I didn't notice that the issue won't be closed if I close the PR :D
