### ISSUE TITLE
Feature request: modifier key or menu in the toolbar

### ISSUE THREAD

**Issue by HubKing** [meetDeveloper/Dictionary-Anywhere#8]
After using it for a while, often it shows the pop-up when I double-click a word just to select it.

Google's dictionary extension on Chrome has settings to show the pop-up only when a modifier key is pressed when double-clicking. This could be useful. 
![image](https://user-images.githubusercontent.com/10900489/66703038-1a3b4c00-ed49-11e9-8447-c948bb456fae.png)

Or, how about showing an icon in the toolbar and show an option to turn double-click detection on/off, plus searching words manually?
![image](https://user-images.githubusercontent.com/10900489/66703060-5a9aca00-ed49-11e9-8ece-2ce82e8b0c86.png)

**Comment by meetDeveloper** [comment]
Nice, I am unfortunately not getting time enough to build this feature, I will sit this weekend and implement this. Thank you for your suggestions.

**Comment by meetDeveloper** [comment]
@HubKing @mpaunovic Added trigger key, update your extension, and see if that works for you.

**Comment by HubKing** [comment]
The modifier key works. Thanks.
