### ISSUE TITLE
Audio not working: Content Security Policy: Blocking insecure request

### ISSUE THREAD

**Issue by sandangel** [meetDeveloper/Dictionary-Anywhere#9]
Audio feature is not working in firefox 71
when I open the console, it has this error:
```sh
Content Security Policy: Blocking insecure request ‘http://ssl.gstatic.com/dictionary/static/sounds/20180430/anywhere--_us_1.mp3’.
```

**Comment by meetDeveloper** [comment]
@sandangel I tested it on firefox 71, Windows 10, it seems to be working in my firefox, are you able to reproduce it?

**Comment by sandangel** [comment]
maybe because it's http. I'm not using this ext anymore. closing

**Comment by meetDeveloper** [comment]
@sandangel Why? Are there any more issue you found?
